<a href="https://colab.research.google.com/github/chirucodes/concepts/blob/master/Executable_Numpy_size_shape_ndim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a_scalar = np.array(20)

In [ ]:
a_scalar

array(20)

In [ ]:
print(a_scalar)

20


In [ ]:
print(type(a_scalar))

<class 'numpy.ndarray'>


In [ ]:
a_scalar.size

1

In [ ]:
a_scalar.shape

()

In [ ]:
a_vector = np.array([1,2,3,4,5])

In [ ]:
a_vector

array([1, 2, 3, 4, 5])

In [ ]:
print(a_vector)

[1 2 3 4 5]


In [ ]:
type(a_vector)

numpy.ndarray

In [ ]:
a_vector.ndim

1

In [ ]:
a_vector.shape

(5,)

In [ ]:
a_vector.size

5

In [ ]:
a_col_vector = np.array([[1],[2],[3],[4],[5]])

In [ ]:
a_col_vector

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
print(a_col_vector)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
a_col_vector.size

5

In [ ]:
a_col_vector.shape

(5, 1)

In [ ]:
a_col_vector.ndim

2

In [ ]:
a_mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
a_mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr1=np.arange(1,13)

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr1.shape

(12,)

In [ ]:
arr1.size

12

In [ ]:
arr2 = np.arange(1,13).reshape(4,3)

In [ ]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
tensor_arr = arr1.reshape(3,2,2)

In [ ]:
tensor_arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
print(tensor_arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
tensor_arr.shape

(3, 2, 2)

In [ ]:
tensor_arr.size

12