<a href="https://colab.research.google.com/github/chirucodes/concepts/blob/master/Executable_B18NumpySession.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a_scalar = np.array(20)

In [3]:
a_scalar

array(20)

In [4]:
print(a_scalar)

20


In [5]:
print(type(a_scalar))

<class 'numpy.ndarray'>


In [15]:
a_scalar.size

1

In [16]:
a_scalar.shape

()

In [6]:
a_vector = np.array([1,2,3,4,5])

In [7]:
a_vector

array([1, 2, 3, 4, 5])

In [8]:
print(a_vector)

[1 2 3 4 5]


In [11]:
type(a_vector)

numpy.ndarray

In [12]:
a_vector.ndim

1

In [13]:
a_vector.shape

(5,)

In [14]:
a_vector.size

5

In [18]:
a_col_vector = np.array([[1],[2],[3],[4],[5]])

In [19]:
a_col_vector

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [20]:
print(a_col_vector)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [21]:
a_col_vector.size

5

In [22]:
a_col_vector.shape

(5, 1)

In [23]:
a_col_vector.ndim

2

In [17]:
a_mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [24]:
a_mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
arr1=np.arange(1,13)

In [30]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
arr1.shape

(12,)

In [32]:
arr1.size

12

In [35]:
arr2 = np.arange(1,13).reshape(4,3)

In [36]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [38]:
tensor_arr = arr1.reshape(3,2,2)

In [39]:
tensor_arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [40]:
print(tensor_arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [41]:
tensor_arr.shape

(3, 2, 2)

In [43]:
tensor_arr.size

12